version: '3.7'

services:

  react:
    build:
      context: .
    ports:
      - "3000:3000"
    container_name: react
    stdin_open: true
    volumes:
       - ./app:/usr/src/app
       - /app/node_modules